set CVSROOT=:pserver:anonymous@cvs-mirror.mozilla.org:/cvsroot
set HOME=F:\moz1.2
set MOZ_CVS_FLAGS=-z3
set MOZCONFIG=F:\moz1.2\mozilla\mozconfig.txt

set MOZ__DEBUG=
set MOZILLA_OFFICIAL=1

set MOZ_BITS=32
set MOZ_TOOLS=F:\moz1.2\moztools\wintools
set OS_TARGET=WINNT
set WINOS=%OS_TARGET%
set _MSC_VER=1200

set DISABLE_TESTS=1
set MOZ_SRC=F:\moz1.2\mozilla
set MOZ_NO_ACTIVEX_SUPPORT=1
set CONFIG_SHELL=SH.EXE

set PATH=%PATH%;%MOZ_TOOLS%\BIN
set PATH=%PATH%;F:\cygwin\bin
REM set PATH=%PATH%;F:\cygwin\bin
set PATH=%PATH%;%MOZ_TOOLS%\include

SET MSVSDIR=C:\Progra~1\micros~2
set INCLUDE=%MSVSDIR%\VC98\Include;%MSVSDIR%\VC98\MFC\Include;%MSVSDIR%\VC98\ATL\Include
SET LIB=%MSVSDIR%\VC98\Lib;%MSVSDIR%\VC98\MFC\Lib

call "C:\Program Files\Microsoft Visual Studio\VC98\Bin\VCVARS32.BAT"